name: machi_koro
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - astroid=2.4.1=py38_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.2.0=py_0
  - autopep8=1.4.4=py_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - colorama=0.4.3=py_0
  - isort=4.3.21=py38_0
  - lazy-object-proxy
  - mccabe=0.6.1=py38_1
  - more-itertools=8.5.0=py_0
  - openssl=1.1.1h
  - packaging=20.4=py_0
  - pip=20.0.2=py38_3
  - pluggy=0.13.1=py38_0
  - py=1.9.0=py_0
  - pycodestyle=2.6.0=py_0
  - pylint=2.5.2=py38_0
  - pyparsing=2.4.7=py_0
  - python=3.8.3
  - rope=0.18.0=py_0
  - setuptools=46.4.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.31.1
  - toml=0.10.0=py_0
  - wheel=0.34.2=py38_0
  - wrapt=1.11.2
  - zlib=1.2.11
  - pip:
      - iniconfig==1.0.1
      - pytest==6.1.1
